#!/bin/bash

## Test mlocarna and locarnate

## perform pseudo installation in subdir bin

if [ -e bin ] ; then rm -rf bin ; fi
mkdir bin

## top level directory of the locarna source
# ---- get the top level by going two levels up from srcdir
topdir=$srcdir/../..

## prefix links to bin files by another ../ since the links reside in bin
ln -sf ../$topdir/src/Utils/mlocarna bin/mlocarna
ln -sf ../$topdir/src/Utils/locarnate bin/locarnate
ln -sf ../../locarna.bin bin/locarna
ln -sf ../../locarna_p bin/locarna_p
ln -sf ../../sparse bin/sparse
ln -sf ../../locarna_rnafold_pp bin/locarna_rnafold_pp

ln -sf $topdir/lib . # also put perl lib modules in the right place

function calltest {
    echo "============================================================"
    echo CALL $*
    echo
    if $* ; then
      echo "======================================== OK"
    else
      echo "======================================== FAILED"
      exit -1
    fi
}

## ========================================
## test mlocarna
##

# examples directory
exdir=$topdir/Data/Examples

# check standard usage with alifold consensus (similar to web server)
calltest bin/mlocarna $exdir/archaea.fa --tgtdir test.out --alifold-cons \
         -p 0.05 --max-diff 10
rm -rf test.out

# check constraints
calltest bin/mlocarna $exdir/haca.snoRNA.fa --tgtdir test.out -p 0.05 \
         --max-diff 20
rm -rf test.out

# check mlocarna sparse
calltest bin/mlocarna $exdir/archaea.fa --tgtdir test.out --sparse -p 0.05 \
         --max-diff 10
rm -rf test.out

# check probabilistic mode and stockholm
calltest bin/mlocarna $exdir/archaea.fa --tgtdir test.out --probabilistic \
         --consistency-transformation -p 0.05  --max-diff 10 --stockholm
rm -rf test.out

# check many threads, and local folding and max-diff-aln
calltest bin/mlocarna $exdir/SECIS_15.fa  --tgtdir test.out --threads 32 \
         --plfold-span 50 --max-diff 10 --max-diff-aln $exdir/SECIS_15_ref.aln
rm -rf test.out

# check anchor constraints from bed file
calltest bin/mlocarna  --anchor-constraints $exdir/haca.snoRNA_anchor.bed $exdir/haca.snoRNA.fa
rm -rf test.out


## ========================================
## test locarnate (if t_coffee is available)
##
calltest bin/locarnate $exdir/archaea.fa
if [ -d "test_results" ] ; then
    rm -rf test_results
fi
if [ -e "input.dnd" ] ; then
    rm -f input.dnd
fi

## cleanup
rm -rf bin
rm -f lib
