# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  my-executor:
    docker:
      - image: ubuntu:jammy

jobs:
  build:
    executor: my-executor

    steps:
      - checkout
      - run:
          name: "Setup environment"
          command: |
            # install via apt
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install --yes --quiet \
              build-essential libtool automake \
              pkg-config \
              doxygen graphviz \
              texlive-latex-base texlive-binaries \
              texlive-latex-recommended \
              texlive-latex-extra \
              wget zip
            #
            # set up conda
            wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
              -O miniconda.sh
            chmod +x miniconda.sh
            ./miniconda.sh -b

            # install via conda
            export PATH="/root/miniconda3/bin:$PATH"
            conda init bash
            conda update --yes -n base -c defaults conda
            conda create --yes -n build -c conda-forge -c bioconda \
              viennarna t_coffee help2man perl

      - run:
          name: "Build"
          command: |
            . ~/miniconda3/etc/profile.d/conda.sh
            . ~/.bashrc
            conda activate build
            autoreconf -i
            ./configure --with-vrna=$CONDA_PREFIX
            make -j

      - run:
          name: "Run checks"
          command: |
            . ~/miniconda3/etc/profile.d/conda.sh
            . ~/.bashrc
            conda activate build
            make check

      - store_artifacts:
          path: src/Tests/test-suite.log

      - run:
          name: "Build packages"
          command: |
            make dist-gzip
            make dist-zip
            mkdir dist
            mv locarna-*.tar.gz dist
            mv locarna-*.zip dist

      - store_artifacts:
          path: dist

      - run:
          name: "Generate documentation"
          command: |
            make doxygen-doc
            tar cvzf documentation.tar.gz Doxy

      - store_artifacts:
          path: documentation.tar.gz


workflows:
  build-and-check:
    jobs:
      - build
