#!/usr/bin/env perl

=head1 NAME

add_newick_intermediate_labels

=head1 SYNOPSIS

add_newick_intermediate_labels [options]

=head1 DESCRIPTION

Add intermediate labels "I#" to inner nodes of a newick tree

=head1 OPTIONS

=over 8

=item  B<--help>

Brief help message

=item  B<--man>                         

Full documentation

=back

=cut


# =item  B<-v, --verbose>

# Verbose

# =item  B<-q, --quiet>

# Quiet


use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib/perl";

use MLocarna::Trees;


##------------------------------------------------------------
## options

use Getopt::Long;
use Pod::Usage;

my $help;
my $man;
my $quiet;
my $verbose;


GetOptions(	   
    "verbose" => \$verbose,
    "quiet" => \$quiet,   
    "help"=> \$help,
    "man" => \$man
    ) || pod2usage(2);

pod2usage(1) if $help;
pod2usage(-exitstatus => 0, -verbose => 2) if $man;


## ------------------------------------------------------------
## main part

sub postorder_tree_to_newick_with_ilables {
    my ($tree_postorder)=@_;
    my $n=0;
    
    my @stack=();
    
    for my $item (@$tree_postorder) {
	if ($item eq $MLocarna::Trees::node_sym) {
	    $n=$n+1;
	    my $y=pop(@stack);
	    my $x=pop(@stack);
	    push @stack,"($x,$y)I$n";
	} else {
	    push @stack,quotemeta($item);
	}
    }
    return $stack[0];
}

while(<>) {
    my $tree_postorder=newick_tree_to_postorder($_);
    
    print postorder_tree_to_newick_with_ilables($tree_postorder).";\n";
}

## ------------------------------------------------------------


